### ISSUE TITLE
When Paw adds it's own default Content-Type, cURL generator does not add it to the generated code

### ISSUE THREAD

**Issue by realrolfje** [luckymarmot/Paw-PHPcURLCodeGenerator#5]
When I configure a POST in Paw with a JSON payload, Paw automatically sends this with the "Content-Type: application/json" header included.

When I generate cURL code for this POST, it does not add that header. That means that the behavior of the cURL generated code is different from the request directly from Paw. This is something I did not expect.

I expected the cURL code to generate the exact same request as Paw would do.

**Comment by realrolfje** [comment]
Looks like Lucky Marmot is not monitoring the GitHub code much. Is this thing on?

**Comment by mittsh** [comment]
@realrolfje sorry I somehow missed the tickets on this repo, this issue has been fixed in an earlier version of Paw, as it was a bug on the app not the actual code generator, it now works fine. In the screenshot below, there is no header explicitly set, but the body is JSON:

![image](https://cloud.githubusercontent.com/assets/1319906/12180226/a2de9e54-b57b-11e5-8b09-9fa818610652.png)

But please make sure you're running the latest version [Paw 2.2.7](https://luckymarmot.com/paw/updates/2.2.7)
